### ISSUE TITLE
We can't pass in the referral code usage_code limit when generating a new referral code

### ISSUE THREAD

**Issue by davidyum** [talon-one/talon_one.py#16]
When we create_referral, the body parameter for [newReferral](https://github.com/talon-one/talon_one.py/blob/master/docs/NewReferral.md) does not take in usage_limit. 
Is there a way we could set the usage_limit when we generate the new code?

**Comment by altJake** [comment]
Hey @davidyum,

Thank you very much for reporting the issue and apologies for us neglecting the Python SDK for so long; It has been a while since we lastly updated it and I am happy to see it is being used.

The latest release ([v3.4.0](https://github.com/talon-one/talon_one.py/releases/tag/v3.4.0)) from today should include the properties your were pointing at righteously.

Thanks again for your contribution, and in case you have any follow up questions, please don't hesitate to drop us a message here!
